<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>aspnet-Hisubmit.Web-9163c27a-a769-440b-9628-a22961fd052d</UserSecretsId>
	</PropertyGroup>
	<ItemGroup>
	  <Content Remove="Components\Pages\Admin\Catalog\AddEditArtCategoryModal.razor" />
	  <Content Remove="Components\Pages\Admin\Catalog\AddEditProductModal.razor" />
	  <Content Remove="Components\Pages\Admin\Catalog\ArtCategories.razor" />
	  <Content Remove="Components\Pages\Admin\Catalog\Products.razor" />
	  <Content Remove="Components\Pages\Admin\FestivalFocuses\AddEditFestivalFocusModal.razor" />
	  <Content Remove="Components\Pages\Admin\FestivalFocuses\FestivalFocus.razor" />
	  <Content Remove="Components\Pages\Festival\DashboardComponent\CategoryDeadLineSubmitChart.razor" />
	  <Content Remove="Components\Pages\Festival\DashboardComponent\CategorySubmitChart.razor" />
	  <Content Remove="Components\Pages\Festival\DashboardComponent\DailySubmitChart.razor" />
	  <Content Remove="Components\Pages\Festival\DashboardComponent\FestivalDetailBox.razor" />
	  <Content Remove="Components\Pages\Festival\DashboardComponent\FestivalImageSlider.razor" />
	  <Content Remove="Components\Pages\Festival\DashboardComponent\FestivalTimeLine.razor" />
	  <Content Remove="Components\Pages\Festival\DashboardComponent\LastSubmitTable.razor" />
	  <Content Remove="Components\Pages\Festival\DashboardComponent\SubmitJudgingStatusChart.razor" />
	  <Content Remove="Components\Pages\Festival\Festival.razor" />
	  <Content Remove="Components\Pages\Festival\JudgingProjects\AddProjectsToRefree.razor" />
	  <Content Remove="Components\Pages\Festival\JudgingProjects\AddReferesToProject.razor" />
	  <Content Remove="Components\Pages\Festival\Judging\AddJudgingButton.razor" />
	  <Content Remove="Components\Pages\Festival\Judging\AddJudgingFiled.razor" />
	  <Content Remove="Components\Pages\Festival\Judging\Judging.razor" />
	  <Content Remove="Components\Pages\Festival\ProjectJudgings\JudgingDetail.razor" />
	  <Content Remove="Components\Pages\Festival\ProjectJudgings\ProjectJudgingForm.razor" />
	  <Content Remove="Components\Pages\Festival\ProjectJudgings\SubmitDetail.razor" />
	  <Content Remove="Components\Pages\Festival\ProjectJudgings\SubmitDetailComponents\SelectedCategories.razor" />
	  <Content Remove="Components\Pages\Festival\ProjectJudgings\SubmitDetailComponents\SubmitFormAnswers.razor" />
	  <Content Remove="Components\Pages\Festival\SubmissionQuestion\AddEditQuestion.razor" />
	  <Content Remove="Components\Pages\Festival\SubmissionQuestion\Questions.razor" />
	  <Content Remove="Components\Pages\Festival\Submits\FinalResultModal.razor" />
	  <Content Remove="Components\Pages\Festival\Submits\SubmitsList.razor" />
	  <Content Remove="Components\Pages\Festival\SubUsers\AddExistingUserToFestivalModal.razor" />
	  <Content Remove="Components\Pages\Festival\SubUsers\FestivalRolePermission.razor" />
	  <Content Remove="Components\Pages\Festival\SubUsers\FestivalRoles.razor" />
	  <Content Remove="Components\Pages\Festival\SubUsers\FestivalSubUser.razor" />
	  <Content Remove="Components\Pages\Festival\SubUsers\FestivalSubUserRoles.razor" />
	  <Content Remove="Components\Pages\Festival\Tickets\Ticket.razor" />
	  <Content Remove="Components\Pages\Festival\Tickets\Tickets.razor" />
	  <Content Remove="Components\Pages\Festival\Tickets\Venue\AddEditShowHall.razor" />
	  <Content Remove="Components\Pages\Festival\Tickets\Venue\VenuesList.razor" />
	  <Content Remove="Components\Pages\User\Communication\Chat.razor" />
	  <Content Remove="Components\Pages\User\Communication\NewChat.razor" />
	  <Content Remove="Components\Pages\User\Referee\Refrees.razor" />
	  <Content Remove="Components\Shared\Components\BlazorHeroLogo.razor" />
	</ItemGroup>
	<ItemGroup>
	  <AdditionalFiles Include="Components\Pages\Admin\Catalog\AddEditArtCategoryModal.razor" />
	  <AdditionalFiles Include="Components\Pages\Admin\Catalog\AddEditProductModal.razor" />
	  <AdditionalFiles Include="Components\Pages\Admin\Catalog\ArtCategories.razor" />
	  <AdditionalFiles Include="Components\Pages\Admin\Catalog\Products.razor" />
	  <AdditionalFiles Include="Components\Pages\Admin\FestivalFocuses\AddEditFestivalFocusModal.razor" />
	  <AdditionalFiles Include="Components\Pages\Admin\FestivalFocuses\FestivalFocus.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\DashboardComponent\CategoryDeadLineSubmitChart.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\DashboardComponent\CategorySubmitChart.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\DashboardComponent\DailySubmitChart.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\DashboardComponent\FestivalDetailBox.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\DashboardComponent\FestivalImageSlider.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\DashboardComponent\FestivalTimeLine.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\DashboardComponent\LastSubmitTable.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\DashboardComponent\SubmitJudgingStatusChart.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\Festival.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\JudgingProjects\AddProjectsToRefree.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\JudgingProjects\AddReferesToProject.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\Judging\AddJudgingButton.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\Judging\AddJudgingFiled.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\Judging\Judging.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\ProjectJudgings\JudgingDetail.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\ProjectJudgings\ProjectJudgingForm.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\ProjectJudgings\SubmitDetail.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\ProjectJudgings\SubmitDetailComponents\SelectedCategories.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\ProjectJudgings\SubmitDetailComponents\SubmitFormAnswers.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\SubmissionQuestion\AddEditQuestion.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\SubmissionQuestion\Questions.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\Submits\FinalResultModal.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\Submits\SubmitsList.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\SubUsers\AddExistingUserToFestivalModal.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\SubUsers\FestivalRolePermission.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\SubUsers\FestivalRoles.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\SubUsers\FestivalSubUser.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\SubUsers\FestivalSubUserRoles.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\Tickets\Ticket.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\Tickets\Tickets.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\Tickets\Venue\AddEditShowHall.razor" />
	  <AdditionalFiles Include="Components\Pages\Festival\Tickets\Venue\VenuesList.razor" />
	  <AdditionalFiles Include="Components\Pages\User\Communication\Chat.razor" />
	  <AdditionalFiles Include="Components\Pages\User\Communication\NewChat.razor" />
	  <AdditionalFiles Include="Components\Pages\User\Referee\Refrees.razor" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.16" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.16" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.16" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.16" />
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.16" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.16" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.16" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.16" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.0.0" />
		<PackageReference Include="DinkToPdf" Version="1.0.8" />
		<PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
		<PackageReference Include="Blazored.FluentValidation" Version="2.1.0" />
		<PackageReference Include="Hangfire" Version="1.8.10" />
		<PackageReference Include="LazyCache.AspNetCore" Version="2.4.0" />
		<PackageReference Include="MediatR" Version="12.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.4" />
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.16" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.16" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.16" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.16" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.0.0" />
		<PackageReference Include="DinkToPdf" Version="1.0.8" />
		<PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
		<PackageReference Include="Blazored.FluentValidation" Version="2.1.0" />
		<PackageReference Include="Hangfire" Version="1.8.10" />
		<PackageReference Include="LazyCache.AspNetCore" Version="2.4.0" />
		<PackageReference Include="MediatR" Version="12.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\HiSubmit\src\Application\Application.csproj" />
		<ProjectReference Include="..\HiSubmit\src\Client.Infrastructure\Client.Infrastructure.csproj" />
		<ProjectReference Include="..\HiSubmit\src\Hisubmit.Hisubmit.Client.SharedModels\Hisubmit.Hisubmit.Client.SharedModels.csproj" />
		<ProjectReference Include="..\HiSubmit\src\Infrastructure\Infrastructure.csproj" />
		<ProjectReference Include="..\HiSubmit\src\Shared\Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Components\Pages\Admin\Festivals\Components\" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="Components\Shared\Components\BlazorHeroLogo.razor" />
	</ItemGroup>

</Project>
