<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>HiSubmit.Application</RootNamespace>
    <AssemblyName>HiSubmit.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="LazyCache" Version="2.4.0" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Client.SharedModels\Client.SharedModels.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Features\Advertises\Queries\" />
    <Folder Include="Features\Locatuions\Addresses\Queries\" />
    <Folder Include="Features\Locatuions\Countries\Commands\" />
    <Folder Include="Features\SpecialAccounts\Commands" />
    <Folder Include="Features\Users\Queries\" />
    <Folder Include="Resources\Features\Festivals\Queries\" />
    <Folder Include="Resources\Features\Users\Queries\" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Features\Festivals\Queries\GetAllShowHall\GetAllShowHallQuery.cs" />
  </ItemGroup>

</Project>
