<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    <RootNamespace>HiSubmit.Client</RootNamespace>
    <AssemblyName>HiSubmit.Client</AssemblyName>
    <BlazorCacheBootResources>false</BlazorCacheBootResources>
	  <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
<!--    <WasmBuildNative>true</WasmBuildNative>-->
<!--    <WasmEnableThreads>true</WasmEnableThreads>-->
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Shared\Components\BlazorHeroLogo.razor" />
    <Content Remove="Shared\Components\FormBuilder.razor" />
    <Content Remove="Routes.razor" />
  </ItemGroup>
	
  <ItemGroup> 
    <PackageReference Include="Blazored.FluentValidation" Version="2.1.0" />
    <PackageReference Include="BlazorVideoPlayer" Version="3.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.4" />
    <!--<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly " Version="8.0.4" />-->
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.4" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
  </ItemGroup>
	
  <ItemGroup>
    <UpToDateCheckInput Remove="Shared\Components\BlazorHeroLogo.razor" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Shared\Components\BlazorHeroLogo.razor" />
    <_ContentIncludedByDefault Remove="Shared\Components\FormBuilder.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\AddEditDeadLineEntry.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\AddEditEventCategory.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\AddEditEventVenueModal.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\AddEditFestivalFileModal.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\AddEventOrginizerModal.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\ContactAndVenue.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\DeadLineEntry.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\EventOrginizer.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\Festival.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\FestivalAdditionalSetting.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\FestivalDeadline.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\FestivalDetail.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\FestivalEventCategory.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\FestivalFile.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\FestivalVenue.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\JudgingProjects\AddProjectsToRefree.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\JudgingProjects\AddReferesToProject.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\Submits\FinalResultModal.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\Submits\SubmitsList.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\SubUsers\AddExistingUserToFestivalModal.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\SubUsers\FestivalRolePermission.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\SubUsers\FestivalRoles.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\SubUsers\FestivalSubUser.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\SubUsers\FestivalSubUserRoles.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\Tickets\Ticket.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\Tickets\Tickets.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\Tickets\Venue\AddEditShowHall.razor" />
    <_ContentIncludedByDefault Remove="Pages\Festival\Tickets\Venue\VenuesList.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\AddEditDeadLineEntry.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\AddEditEventCategory.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\AddEditEventVenueModal.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\AddEditFestivalFileModal.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\AddEventOrginizerModal.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\ContactAndVenue.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\DeadLineEntry.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\EventOrginizer.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\Festival.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\FestivalAdditionalSetting.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\FestivalDeadline.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\FestivalDetail.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\FestivalEventCategory.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\FestivalFile.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\FestivalVenue.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\JudgingProjects\AddProjectsToRefree.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\JudgingProjects\AddReferesToProject.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\Submits\FinalResultModal.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\Submits\SubmitsList.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\SubUsers\AddExistingUserToFestivalModal.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\SubUsers\FestivalRolePermission.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\SubUsers\FestivalRoles.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\SubUsers\FestivalSubUser.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\SubUsers\FestivalSubUserRoles.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\Tickets\Ticket.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\Tickets\Tickets.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\Tickets\Venue\AddEditShowHall.razor" />
    <_ContentIncludedByDefault Remove="Shared\Festival\Tickets\Venue\VenuesList.razor" />
    <_ContentIncludedByDefault Remove="Pages\Content\DashboardComponent\CategoryDeadLineSubmitChart.razor" />
    <_ContentIncludedByDefault Remove="Pages\Content\DashboardComponent\CategorySubmitChart.razor" />
    <_ContentIncludedByDefault Remove="Pages\Content\DashboardComponent\DailySubmitChart.razor" />
    <_ContentIncludedByDefault Remove="Pages\Content\DashboardComponent\FestivalDetailBox.razor" />
    <_ContentIncludedByDefault Remove="Pages\Content\DashboardComponent\FestivalImageSlider.razor" />
    <_ContentIncludedByDefault Remove="Pages\Content\DashboardComponent\FestivalTimeLine.razor" />
    <_ContentIncludedByDefault Remove="Pages\Content\DashboardComponent\LastSubmitTable.razor" />
    <_ContentIncludedByDefault Remove="Pages\Content\DashboardComponent\SubmitJudgingStatusChart.razor" />
    <_ContentIncludedByDefault Remove="Pages\FestivalFocuses\AddEditFestivalFocusModal.razor" />
    <_ContentIncludedByDefault Remove="Pages\FestivalFocuses\FestivalFocus.razor" />
    <_ContentIncludedByDefault Remove="Pages\Catalog\AddEditArtCategoryModal.razor" />
    <_ContentIncludedByDefault Remove="Pages\Catalog\AddEditProductModal.razor" />
    <_ContentIncludedByDefault Remove="Pages\Catalog\ArtCategories.razor" />
    <_ContentIncludedByDefault Remove="Pages\Catalog\Products.razor" />
    <_ContentIncludedByDefault Remove="Pages\Judging\AddJudgingButton.razor" />
    <_ContentIncludedByDefault Remove="Pages\Judging\AddJudgingFiled.razor" />
    <_ContentIncludedByDefault Remove="Pages\Judging\Judging.razor" />
    <_ContentIncludedByDefault Remove="Pages\Content\Home.razor" />
    <_ContentIncludedByDefault Remove="Pages\Communication\Chat.razor" />
    <_ContentIncludedByDefault Remove="Pages\Communication\NewChat.razor" />
    <_ContentIncludedByDefault Remove="Pages\Test\TestPage.razor" />
    <_ContentIncludedByDefault Remove="Pages\SubmissionQuestion\AddEditQuestion.razor" />
    <_ContentIncludedByDefault Remove="Pages\SubmissionQuestion\Questions.razor" />
    <_ContentIncludedByDefault Remove="Pages\Refree\Refrees.razor" />
    <_ContentIncludedByDefault Remove="Pages\ProjectJudging\JudgingDetail.razor" />
    <_ContentIncludedByDefault Remove="Pages\ProjectJudging\ProjectJudgingForm.razor" />
    <_ContentIncludedByDefault Remove="Pages\ProjectJudging\SubmitDetail.razor" />
    <_ContentIncludedByDefault Remove="Pages\ProjectJudging\SubmitDetailComponents\SelectedCategories.razor" />
    <_ContentIncludedByDefault Remove="Pages\ProjectJudging\SubmitDetailComponents\SubmitFormAnswers.razor" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Shared\Components\BlazorHeroLogo.razor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Client.Infrastructure\Client.Infrastructure.csproj" />
    <ProjectReference Include="..\Client.SharedModels\Client.SharedModels.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Shared\Components\FormBuilder.razor" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Pages\Admin\Catalog\AddEditArtCategoryModal.razor" />
    <AdditionalFiles Include="Pages\Admin\Catalog\AddEditProductModal.razor" />
    <AdditionalFiles Include="Pages\Admin\Catalog\ArtCategories.razor" />
    <AdditionalFiles Include="Pages\Admin\Catalog\Products.razor" />
    <AdditionalFiles Include="Pages\Admin\FestivalFocuses\AddEditFestivalFocusModal.razor" />
    <AdditionalFiles Include="Pages\Admin\FestivalFocuses\FestivalFocus.razor" />
    <AdditionalFiles Include="Pages\Festival\DashboardComponent\CategoryDeadLineSubmitChart.razor" />
    <AdditionalFiles Include="Pages\Festival\DashboardComponent\CategorySubmitChart.razor" />
    <AdditionalFiles Include="Pages\Festival\DashboardComponent\DailySubmitChart.razor" />
    <AdditionalFiles Include="Pages\Festival\DashboardComponent\FestivalDetailBox.razor" />
    <AdditionalFiles Include="Pages\Festival\DashboardComponent\FestivalImageSlider.razor" />
    <AdditionalFiles Include="Pages\Festival\DashboardComponent\FestivalTimeLine.razor" />
    <AdditionalFiles Include="Pages\Festival\DashboardComponent\LastSubmitTable.razor" />
    <AdditionalFiles Include="Pages\Festival\DashboardComponent\SubmitJudgingStatusChart.razor" />
    <AdditionalFiles Include="Pages\Festival\Festival.razor" />
    <AdditionalFiles Include="Pages\Festival\JudgingProjects\AddProjectsToRefree.razor" />
    <AdditionalFiles Include="Pages\Festival\JudgingProjects\AddReferesToProject.razor" />
    <AdditionalFiles Include="Pages\Festival\Judging\AddJudgingButton.razor" />
    <AdditionalFiles Include="Pages\Festival\Judging\AddJudgingFiled.razor" />
    <AdditionalFiles Include="Pages\Festival\Judging\Judging.razor" />
    <AdditionalFiles Include="Pages\Festival\ProjectJudgings\JudgingDetail.razor" />
    <AdditionalFiles Include="Pages\Festival\ProjectJudgings\ProjectJudgingForm.razor" />
    <AdditionalFiles Include="Pages\Festival\ProjectJudgings\SubmitDetail.razor" />
    <AdditionalFiles Include="Pages\Festival\ProjectJudgings\SubmitDetailComponents\SelectedCategories.razor" />
    <AdditionalFiles Include="Pages\Festival\ProjectJudgings\SubmitDetailComponents\SubmitFormAnswers.razor" />
    <AdditionalFiles Include="Pages\Festival\SubmissionQuestion\AddEditQuestion.razor" />
    <AdditionalFiles Include="Pages\Festival\SubmissionQuestion\Questions.razor" />
    <AdditionalFiles Include="Pages\Festival\Submits\FinalResultModal.razor" />
    <AdditionalFiles Include="Pages\Festival\Submits\SubmitsList.razor" />
    <AdditionalFiles Include="Pages\Festival\SubUsers\AddExistingUserToFestivalModal.razor" />
    <AdditionalFiles Include="Pages\Festival\SubUsers\FestivalRolePermission.razor" />
    <AdditionalFiles Include="Pages\Festival\SubUsers\FestivalRoles.razor" />
    <AdditionalFiles Include="Pages\Festival\SubUsers\FestivalSubUser.razor" />
    <AdditionalFiles Include="Pages\Festival\SubUsers\FestivalSubUserRoles.razor" />
    <AdditionalFiles Include="Pages\Festival\Tickets\Ticket.razor" />
    <AdditionalFiles Include="Pages\Festival\Tickets\Tickets.razor" />
    <AdditionalFiles Include="Pages\Festival\Tickets\Venue\AddEditShowHall.razor" />
    <AdditionalFiles Include="Pages\Festival\Tickets\Venue\VenuesList.razor" />
    <AdditionalFiles Include="Pages\User\Communication\Chat.razor" />
    <AdditionalFiles Include="Pages\User\Communication\NewChat.razor" />
    <AdditionalFiles Include="Pages\User\Referee\Refrees.razor" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\Admin\Festivals\Components" />
  </ItemGroup>

</Project>
